# This limits how many songs will be searched by the !search function
search_limit: 3

# How many seconds a song must be played before it can be skipped
skip_grace: 5

# How many items need to be in the queue before it becomes moderator-only
public_queue_max: 10

# How long the vc should be empty in minutes until the queue gets cleared. -1 to disable
clear_time: 10

# The bot will auto-join and start playing in these.
# <guild id>: <voice channel id>
default_channels:
  184755239952318464: 334325676469518337
  297811083308171264: 297811083308171266

# These are the channels where the bot will respond to user commands.
# If not specified, the bot will respond in all channels.
# <guild id>: [<text channel id>, <text channel id>, ...]
bot_channels:
  184755239952318464: [334296431789604864]
  297811083308171264: [297811083308171264]

# This is the location of the bot's credentials. See creds.yml.template
creds_file: config/creds.yml

# These are the people the bot DMs when something goes wrong
# Add yourself here if you want to know when something goes wrong
developers:
  - 240995021208289280

# It's the prefix.. What more do I need to say?
command_prefix: "!"
