# No song may be queued that is longer than this (s) except by someone
# with the 'Manage Channels' permission.
max_song_length: 900

# This is the number of songs that a user may have in the queue at one
# time. Excludes members with the 'Manage Channels' permission.
max_songs_queued: 1

# The bot will auto-join and start playing in these.
# <guild id>: <voice channel id>
default_channels:
  290573725366091787: 290573725366091788
  297811083308171264: 297811083308171266
  184755239952318464: 334325676469518337

# These are the channels where the bot will respond to user commands.
# If not specified, the bot will respond in all channels.
# <guild id>: [<text channel id>, <text channel id>, ...]
bot_channels:
  184755239952318464: [334296431789604864]
  290573725366091787: [290757101914030080, 290756934523551744]
  297811083308171264: [297811083308171264]

# This is the location of the bot's token. The token must be placed on
# the first line of the file
token_file: config/token.txt

# This is the change that a jingle will play instead of an auto-playlist
# song.
# The chance is `1/jingle_chance`
jingle_chance: 5

# It's the prefix.. What more do I need to say?
command_prefix: "!"
