# The bot will auto-join and start playing in these.
# <guild id>: <voice channel id>
184755239952318464: 334325676469518337  # HTC
297811083308171264: 297811083308171266  # Hanss' testing server
381941901462470658: 381941901961461763  # Chilled Prophecies
290573725366091787: 315434165921382401  # Bottersnike Bot Testing
