# yay!
patrons:
  319350638024720384: # Space Witch
    pledge: 3
  154825973278310400: # Satomi
    pledge: 1
  198191547970355200: # sills dog
    pledge: 1
  193874867324583936: # Eli / anonymouse
    pledge: 1
